sudo: required
language: python
python:
    - "3.8"

install:
    - pip3 install -r requirements.txt

script:
    - pip3 install nltk
    - cd ../../../virtualenv && pwd && ls
    - sudo python3 -m ../../../virtualenv/python3.8.7/lib/python3.8/site-packages/nltk/nltk.downloader -d /usr/share/nltk_data all
    - ./test.sh
    - python3 -m populate_mock_users