sudo: required
language: python
python:
    - "3.8"

install:
    - pip3 install -r requirements.txt

script:
    - python3 -m nltk.downloader -d /usr/share/nltk_data all
    - ./test.sh
    - python3 -m populate_mock_users