sudo: required
language: python
python:
    - "3.8"

install:
    - pip3 install -r requirements.txt

script:
    - pwd && ls
    - cp -R nltk_data ../../../nltk_data
    - ./test.sh
    - python3 -m populate_mock_users